version: "3.9"  # optional since v1.27.0

services:
  spxwebapi:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@Sql2019"
      MSSQL_PID: Express
    ports:
      - "1433:1433"